version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  commands:
    - pip install zensical
    - zensical build --clean
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r site/* $READTHEDOCS_OUTPUT/html/